version: "3"
services:
  db:
    hostname: ma0-tdi-mariadb
    image: mariadb
    container_name: ma0-tdi-mariadb
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass@1234
      MYSQL_DATABASE: alocadb
      MYSQL_USER: acess
      MYSQL_PASSWORD: pass@1234
    ports:
      - 7001:3306

  web:
    hostname: ma0-tdi-php-apache
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: ma0-tdi-php-apache:1.0
    container_name: ma0-tdi-php-apache
    networks:
      - backend
      - frontend
    depends_on:
      - db
    volumes:
      - ./.docker/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./php/:/var/www/html
    ports:
      - 7000:80

  phpmyadmin:
    hostname: ma0-tdi-phpmyadmin
    container_name: ma0-tdi-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: pass@1234
      MYSQL_USER: access
      MYSQL_PASSWORD: pass@1234
    networks:
      - backend
      - frontend
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 7002:80

networks:
  backend:
  frontend:
